/* ─────────────────────────────────────────────
   Home & Über uns — dashboard sections for texts that used to be
   hard-coded in components (content review 30.09.2026).
   Components read them via useReviewText(sectionKey).
───────────────────────────────────────────── */
import type { TextEntry, TextSection } from './textStore';

type EntryType = TextEntry['type'];
const e = (id: string, label: string, type: EntryType, value: string): TextEntry => ({
  id, label, description: '', type, value, ...(value.length > 80 ? { multiline: true } : {}),
});

export const REVIEW_TEXT_SECTIONS: TextSection[] = [
  {
    key: 'common_srt_data_nodes', label: 'SRT — Datenfluss-Knoten (Home & SRT)', pageGroupId: 'srt', pagePath: '/srt', description: 'Beschreibungen der vier Datenquellen im Datenfluss-Diagramm (Home-Teaser und SRT-Seite).',
    entries: [
      e('n1-desc', 'Sonic-Daten — Text', 'caption', 'Einsatzplanung & Kampagnenstatus in Echtzeit'),
      e('n2-desc', 'Externe Daten — Text', 'caption', 'Handelsdaten, Online-Shops & Hersteller-Apps'),
      e('n3-desc', 'Kunden-Daten — Text', 'caption', 'Live-KPIs, Abverkauf & Reportings'),
      e('n4-desc', 'Mitarbeiter-Daten — Text', 'caption', 'Einsatztracking, Ziele & Abrechnung'),
    ],
  },
  {
    key: 'home_metrics', label: 'LiveMetrics — Kennzahlen-Ticker', pageGroupId: 'home', pagePath: '/', description: 'Laufband unter dem Hero.',
    entries: [
      e('m1-value', 'Kennzahl 1 — Wert', 'stat', '>2 Mrd. €'),
      e('m1-label', 'Kennzahl 1 — Label', 'stat-label', 'Umsatz für unsere Kunden'),
      e('m2-value', 'Kennzahl 2 — Wert', 'stat', '>1,3 Mio.'),
      e('m2-label', 'Kennzahl 2 — Label', 'stat-label', 'erledigte Einsätze'),
      e('m3-value', 'Kennzahl 3 — Wert', 'stat', '>1.000'),
      e('m3-label', 'Kennzahl 3 — Label', 'stat-label', 'betreute Stores'),
      e('m4-value', 'Kennzahl 4 — Wert', 'stat', '200+'),
      e('m4-label', 'Kennzahl 4 — Label', 'stat-label', 'Promoter:innen im Einsatz'),
      e('m5-value', 'Kennzahl 5 — Wert', 'stat', '>1.800'),
      e('m5-label', 'Kennzahl 5 — Label', 'stat-label', 'Menschen im Talentpool'),
      e('m6-value', 'Kennzahl 6 — Wert', 'stat', '>47.000'),
      e('m6-label', 'Kennzahl 6 — Label', 'stat-label', 'Live-Beratungen'),
    ],
  },
  {
    key: 'home_video_texts', label: 'VideoShowcase — Texte', pageGroupId: 'home', pagePath: '/', description: 'Unterzeile und Leiste unter dem Video.',
    entries: [
      e('sub', 'Unterzeile', 'paragraph', 'So verkauft Sonic Marken am POS, im Studio und auf Events — mit Menschen, die Marken erlebbar machen.'),
      e('strip-1', 'Leiste 1', 'caption', 'Seit 2007'),
      e('strip-2', 'Leiste 2', 'caption', 'DACH-weit'),
      e('strip-3', 'Leiste 3', 'caption', 'Messbar im SRT'),
    ],
  },
  {
    key: 'home_services_texts', label: 'ServicesGrid — Leistungen (Tabs)', pageGroupId: 'home', pagePath: '/', description: 'Einleitung und die fünf Leistungs-Tabs.',
    entries: [
      e('intro', 'Einleitung unter „Manpower trifft ROI“', 'paragraph', 'POS Full Service, Events & Messen, Kreation & Content, Schulungen und Live Video – ein Partner, ein Team, eine Datenbasis.'),
      e('tab1-short', 'Tab 1 — Kurzname', 'label', 'POS Full Service'),
      e('tab1-title', 'Tab 1 — Titel', 'heading', 'Menschen für Promotion & POS'),
      e('tab1-lead', 'Tab 1 — Leadzeile', 'label', 'Geschultes Personal mit Augenmerk auf Marken- und / oder Produkt-Inszenierung.'),
      e('tab1-desc', 'Tab 1 — Text', 'paragraph', 'Geschulte Promoter:innen beraten und verkaufen direkt an deiner Fläche. Mit POS Full Service kommt alles Weitere aus einer Hand: Displays, Möbel, Collateral, Logistik und Montage — datenbasiert geplant, live reportet und messbar erfolgreich.'),
      e('tab1-tagline', 'Tab 1 — Belegzeile', 'caption', 'Menschen, die verkaufen. Flächen, die wirken.'),
      e('tab2-short', 'Tab 2 — Kurzname', 'label', 'Events & Messen'),
      e('tab2-title', 'Tab 2 — Titel', 'heading', 'Menschen für Events & Messen'),
      e('tab2-lead', 'Tab 2 — Leadzeile', 'label', 'Dediziert geschultes Personal für bestimmte Funktionen – Moderation, Musik, Catering, Logistik und Aufbau.'),
      e('tab2-desc', 'Tab 2 — Text', 'paragraph', 'Wir präsentieren deine Marke da, wo deine Zielgruppe ist: Events, Messen, Roadshows und hybride Formate. Von Konzept über Personal bis Logistik — alles aus einer Hand.'),
      e('tab2-tagline', 'Tab 2 — Belegzeile', 'caption', 'Über 200 Events. Über 30.000 Kontakte. Vor Ort, auf Tour, mit Wirkung.'),
      e('tab3-short', 'Tab 3 — Kurzname', 'label', 'Kreation & Content'),
      e('tab3-title', 'Tab 3 — Titel', 'heading', 'Menschen für Content'),
      e('tab3-lead', 'Tab 3 — Leadzeile', 'label', 'Ausdrucksstarkes Personal mit Fokus auf Content Produktion.'),
      e('tab3-desc', 'Tab 3 — Text', 'paragraph', 'Unboxing- und How-to-Videos, Foto- und Videoshootings, Livestreams, Produktvideos und Social Media — mit ausdrucksstarkem Personal vor und hinter der Kamera.'),
      e('tab3-tagline', 'Tab 3 — Belegzeile', 'caption', 'Von Social Content bis Livestreams und Produktvideos — Content mit Retail-DNA.'),
      e('tab4-short', 'Tab 4 — Kurzname', 'label', 'Schulungen'),
      e('tab4-title', 'Tab 4 — Titel', 'heading', 'Menschen für Schulungen'),
      e('tab4-lead', 'Tab 4 — Leadzeile', 'label', 'Für Marken-, Produkt- und Verkaufs-Training.'),
      e('tab4-desc', 'Tab 4 — Text', 'paragraph', 'Menschen, die Marken erklären. Trainings, die Wissen direkt in Performance verwandeln — offline, hybrid oder online. Mit Personal und Technik aus einem System.'),
      e('tab4-tagline', 'Tab 4 — Belegzeile', 'caption', 'Strategisch geplant. Praxisnah umgesetzt.'),
      e('tab5-short', 'Tab 5 — Kurzname', 'label', 'Live Video'),
      e('tab5-title', 'Tab 5 — Titel', 'heading', 'Menschen für unsere Studios'),
      e('tab5-lead', 'Tab 5 — Leadzeile', 'label', 'All In One: Regisseur, Moderator, Verkäufer.'),
      e('tab5-desc', 'Tab 5 — Text', 'paragraph', 'Erlebbar werden: Produktberatung, Sales und Service-Support direkt aus unseren Studio-Setups. Für Livestreams, Video-Commerce, digitale Beratung und Content-Produktion.'),
      e('tab5-tagline', 'Tab 5 — Belegzeile', 'caption', 'Ø 5,5 Minuten Gesprächsdauer. Über 4.200 Stunden Beratungszeit.'),
    ],
  },
  {
    key: 'home_srt_teaser', label: 'SRTTeaser — Kopf & Unterzeile', pageGroupId: 'home', pagePath: '/', description: 'Kicker, Überschrift und Text im SRT-Teaser.',
    entries: [
      e('eyebrow', 'Kicker', 'badge', 'Reporting & Steuerung'),
      e('heading', 'Überschrift (weiß)', 'heading', 'Sonic Reporting Tool'),
      e('heading-accent', 'Überschrift — Akzent (lime)', 'heading', '(SRT)'),
      e('sub', 'Unterzeile', 'paragraph', 'Seit 2008 unser eigenes Tool: individualisierbar, mehrsprachig, adaptiv. Über 21 Versionen – jeder Einsatz wird darin gesteuert, und du siehst deine Projektdaten live.'),
    ],
  },
  {
    key: 'home_drive_cards', label: 'Was uns antreibt — Karten 01/02', pageGroupId: 'home', pagePath: '/', description: 'Zwei Zeilen in der dunklen Box „Was uns antreibt“.',
    entries: [
      e('c1-eyebrow', 'Karte 01 — Kicker', 'label', 'Daten'),
      e('c1-title', 'Karte 01 — Titel', 'subheading', 'Messbar statt Bauchgefühl'),
      e('c1-text', 'Karte 01 — Text', 'paragraph', '— Analyse, Herleitung, Sicherheit statt Bauchgefühl – jede Maßnahme wird im SRT messbar.'),
      e('c1-tags', 'Karte 01 — Pills (mit Komma trennen)', 'tag', 'Analyse, Herleitung, SRT'),
      e('c2-eyebrow', 'Karte 02 — Kicker', 'label', 'Mensch'),
      e('c2-title', 'Karte 02 — Titel', 'subheading', 'Das passende Team'),
      e('c2-text', 'Karte 02 — Text', 'paragraph', '— Aus unserem Talentpool stellen wir für jedes Projekt das Team zusammen, das zu deiner Marke passt.'),
      e('c2-tags', 'Karte 02 — Pills (mit Komma trennen)', 'tag', 'Talentpool, Live-Einblick, Motivation'),
    ],
  },
  {
    key: 'home_closing_cta', label: 'Abschluss-CTA (Home)', pageGroupId: 'home', pagePath: '/', description: 'Box am Seitenende nach „Was uns antreibt“ (Button: „Termin vereinbaren“).',
    entries: [
      e('headline', 'Überschrift', 'heading', 'Bereit für den'),
      e('headline-accent', 'Überschrift — Akzent (lime)', 'heading', 'nächsten Schritt?'),
      e('subline', 'Zeile', 'paragraph', 'Erzähl uns von deinem Vorhaben – wir zeigen dir, welcher Weg zu deiner Marke passt.'),
    ],
  },
  {
    key: 'about_ticker', label: 'Über uns — Kennzahlen-Ticker', pageGroupId: 'about', pagePath: '/ueber-uns', description: 'Laufband unter „Marken im Herzen“, Badge und Karte am Bild.',
    entries: [
      e('t1-value', 'Kennzahl 1 — Wert', 'stat', '>15'),
      e('t1-label', 'Kennzahl 1 — Label', 'stat-label', 'Kunden'),
      e('t2-value', 'Kennzahl 2 — Wert', 'stat', '>1,3 Mio.'),
      e('t2-label', 'Kennzahl 2 — Label', 'stat-label', 'Einsätze'),
      e('t3-value', 'Kennzahl 3 — Wert', 'stat', '>1.000'),
      e('t3-label', 'Kennzahl 3 — Label', 'stat-label', 'Stores'),
      e('t4-value', 'Kennzahl 4 — Wert', 'stat', '2007'),
      e('t4-label', 'Kennzahl 4 — Label', 'stat-label', 'Gegründet'),
      e('t5-value', 'Kennzahl 5 — Wert', 'stat', '200+'),
      e('t5-label', 'Kennzahl 5 — Label', 'stat-label', 'Promoter:innen im Einsatz'),
      e('t6-value', 'Kennzahl 6 — Wert', 'stat', '>1.800'),
      e('t6-label', 'Kennzahl 6 — Label', 'stat-label', 'Menschen im Talentpool'),
      e('t7-value', 'Kennzahl 7 — Wert', 'stat', 'DACH'),
      e('t7-label', 'Kennzahl 7 — Label', 'stat-label', 'Marktabdeckung'),
      e('t8-value', 'Kennzahl 8 — Wert', 'stat', '>2 Mrd. €'),
      e('t8-label', 'Kennzahl 8 — Label', 'stat-label', 'Umsatz für unsere Kunden'),
      e('img-badge', 'Badge auf dem Bild', 'badge', 'Sonic Group'),
      e('float-value', 'Karte am Bild — Wert', 'stat', 'Krefeld'),
      e('float-label', 'Karte am Bild — Label', 'stat-label', 'Unser Campus & Studio'),
    ],
  },
  {
    key: 'about_values_texts', label: 'Über uns — Referenzen & Team-Kennzahlen', pageGroupId: 'about', pagePath: '/ueber-uns', description: 'Zeile über den Referenz-Logos und die drei Team-Kennzahlen.',
    entries: [
      e('refs-line', 'Referenzen — Zeile', 'paragraph', 'Unsere Kunden – im Studio, auf der Fläche, im Fachhandel, in Sport & Freizeit und im B2B.'),
      e('team1-value', 'Team-Kennzahl 1 — Wert', 'stat', '5,4'),
      e('team1-unit', 'Team-Kennzahl 1 — Einheit', 'label', 'Jahre'),
      e('team1-label', 'Team-Kennzahl 1 — Label', 'stat-label', 'Ø Betriebszugehörigkeit Sonic-Team'),
      e('team2-value', 'Team-Kennzahl 2 — Wert', 'stat', 'Dual'),
      e('team2-unit', 'Team-Kennzahl 2 — Einheit', 'label', 'Studium'),
      e('team2-label', 'Team-Kennzahl 2 — Label', 'stat-label', 'Ausbildungspartner'),
      e('team3-value', 'Team-Kennzahl 3 — Wert', 'stat', 'B2B + D2C'),
      e('team3-unit', 'Team-Kennzahl 3 — Einheit', 'label', ''),
      e('team3-label', 'Team-Kennzahl 3 — Label', 'stat-label', 'Kunden- & Agenturseite'),
    ],
  },
  /* CTA review 30.09.2026 — lean CTA texts that used to be hard-coded.
     Button labels themselves live in „CTAs — Button-Texte (alle Seiten)“. */
  {
    key: 'home_quiz_result_cta', label: 'Kurzumfrage — Ergebnis-CTA', pageGroupId: 'home', pagePath: '/', description: 'Empfehlung (Titel/Text je Ergebnis) und Zeile über dem Termin-Button im Ergebnis der Kurzumfrage.',
    entries: [
      e('eyebrow', 'Kicker über der Empfehlung', 'label', 'Deine empfohlene Lösung'),
      e('line', 'Zeile', 'paragraph', 'In 30 Minuten klären wir, was zu deinem Ziel passt.'),
      e('alt-question', 'Frage unten', 'label', 'Nicht ganz passend?'),
      e('alt-link', 'Link unten (führt zum Kontaktformular)', 'link', 'Direkt mit unserem Team sprechen →'),
      e('market-entry-title', 'Ergebnis Markteintritt — Titel', 'heading', 'Markteintritts-Strategie'),
      e('market-entry-desc', 'Ergebnis Markteintritt — Text', 'paragraph', 'Du brauchst einen erprobten Partner, der dich durch DACH-Regularien, Handelsbeziehungen und lokale Marktdynamiken führt.'),
      e('retail-pos-title', 'Ergebnis Retail-Präsenz — Titel', 'heading', 'POS Full Service'),
      e('retail-pos-desc', 'Ergebnis Retail-Präsenz — Text', 'paragraph', 'Baue deine Retail-Präsenz mit professionellem Merchandising, POS-Umsetzung und In-Store-Performance-Optimierung aus.'),
      e('staffing-title', 'Ergebnis Personal — Titel', 'heading', 'Staff as a Service'),
      e('staffing-desc', 'Ergebnis Personal — Text', 'paragraph', 'Zugriff auf qualifizierte, geschulte Promoter:innen, die deine Marke in ganz DACH vertreten.'),
      e('events-title', 'Ergebnis Events — Titel', 'heading', 'Events & Messen'),
      e('events-desc', 'Ergebnis Events — Text', 'paragraph', 'Führe Events und Messen mit erfahrenem Personal, Logistik-Support und Echtzeit-Reporting reibungslos durch.'),
    ],
  },
  {
    key: 'casestudies_inline_cta', label: 'Fallbeispiele — Story-Button & CTA in der Story', pageGroupId: 'case_studies', pagePath: '/fallbeispiele', description: 'Button im Story-Slider und Box unter einer geöffneten Story (Button: „Projekt anfragen“).',
    entries: [
      e('read-story', 'Button im Slider — Story öffnen', 'cta', 'Story lesen'),
      e('headline', 'Frage', 'subheading', 'Deine Marke als Nächstes?'),
      e('line', 'Zeile', 'paragraph', 'Erzähl uns kurz von deinem Projekt.'),
    ],
  },
  {
    key: 'casestudies_card_texts', label: 'Fallbeispiele — Einzeltexte (Karten & Module)', pageGroupId: 'case_studies', pagePath: '/fallbeispiele', description: 'Kampagnen-Label der Garmin-Karte und einzelne Modul-Texte der Stories.',
    entries: [
      e('garmin-campaign', 'Garmin — Kampagnen-Label', 'label', 'Retail Activation & POS Full Service'),
      e('seb-module-4-desc', 'Groupe SEB — Modul 04 Text', 'paragraph', 'Unsere Promoter:innen als Markenbotschafter, Verkäufer und Servicekräfte am POS.'),
      e('avoury-module-2-desc', 'Avoury — Modul 02 Text', 'paragraph', 'Vor den Einsätzen: Schulungen der Promoter:innen an unserem Campus in Krefeld — Produktwissen, Gesprächsführung, Cross-Selling-Methode.'),
    ],
  },
  {
    key: 'srt_cta_texts', label: 'SRT — CTA-Texte (Demo)', pageGroupId: 'srt', pagePath: '/srt', description: 'Demo-Boxen unter „Funktionsumfang“ und unter den Geräten sowie die Zugangs-Box mit Formular.',
    entries: [
      e('demo', 'Button — Demo anfragen (Geräte-Box & Formular)', 'cta', 'Demo anfragen'),
      e('features-headline', 'Box Funktionsumfang — Frage', 'subheading', 'Noch Fragen zum Funktionsumfang?'),
      e('features-line', 'Box Funktionsumfang — Zeile', 'paragraph', 'Wir zeigen dir das SRT live.'),
      e('showcase-headline', 'Box unter den Geräten — Frage', 'subheading', 'SRT live sehen?'),
      e('showcase-line', 'Box unter den Geräten — Zeile', 'paragraph', 'Wir richten dir einen Demo-Zugang ein.'),
      e('access-headline', 'Zugang — Frage (weiß)', 'heading', 'SRT'),
      e('access-accent', 'Zugang — Frage (lime)', 'heading', 'kennenlernen?'),
      e('access-line', 'Zugang — Zeile', 'paragraph', 'Wir zeigen dir in 30 Minuten, wie das SRT für dein Projekt aussieht.'),
      e('form-note', 'Formular — Zeile unter dem Button', 'caption', 'Kostenlos & unverbindlich'),
      e('form-success', 'Formular — Bestätigung', 'paragraph', 'Wir melden uns zeitnah.'),
    ],
  },
  /* ── SRT content review 30.09.2026 (Agenturpräsentation 2026) — texts that used to be hard-coded ── */
  {
    key: 'srt_features_cards', label: 'SRT — All-in-One: Kacheln', pageGroupId: 'srt', pagePath: '/srt', description: 'Die sechs Kacheln unter „SRT: Die All-in-One Software“, die Unterzeile und die kleine Zeile rechts neben dem Badge.',
    entries: [
      e('meta', 'Zeile rechts neben dem Badge', 'caption', 'Für Kunden & Teams'),
      e('sub', 'Unterzeile neben der Überschrift', 'paragraph', 'Laufend weiterentwickelt, für maximalen Nutzwert – inklusive KI-Features.'),
      e('f1-title', 'Kachel 1 — Titel', 'heading', 'Echtzeit-Dashboard'),
      e('f1-desc', 'Kachel 1 — Text', 'paragraph', 'Alle gewünschten Metriken auf einen Blick — live und übersichtlich dargestellt, für schnellere Entscheidungen.'),
      e('f1-tag-1', 'Kachel 1 — Tag 1', 'label', 'Live-Daten'),
      e('f1-tag-2', 'Kachel 1 — Tag 2', 'label', 'KPIs'),
      e('f1-tag-3', 'Kachel 1 — Tag 3', 'label', 'Echtzeit'),
      e('f2-title', 'Kachel 2 — Titel', 'heading', 'Performance-Tracking'),
      e('f2-desc', 'Kachel 2 — Text', 'paragraph', 'Verkaufszahlen, Top-/Flop-Listen.'),
      e('f3-title', 'Kachel 3 — Titel', 'heading', 'Team-Management'),
      e('f3-desc', 'Kachel 3 — Text', 'paragraph', 'Recruiting, Einsätze, GPS-genau.'),
      e('f4-title', 'Kachel 4 — Titel', 'heading', 'Reportings'),
      e('f4-desc', 'Kachel 4 — Text', 'paragraph', 'Excel, PPT, SQL.'),
      e('f5-title', 'Kachel 5 — Titel', 'heading', 'Mobile App'),
      e('f5-desc', 'Kachel 5 — Text', 'paragraph', 'Mobil. Einhändig. Intuitiv.'),
      e('f6-title', 'Kachel 6 — Titel', 'heading', 'Datensicherheit'),
      e('f6-desc', 'Kachel 6 — Text', 'paragraph', 'DSGVO-konform.'),
    ],
  },
  {
    key: 'srt_showcase_texts', label: 'SRT — Produkt (Desktop & Mobil)', pageGroupId: 'srt', pagePath: '/srt', description: 'Abschnitt „Das Produkt“ mit Laptop- und Smartphone-Mock-up, den vier App-Kacheln und der Leiste darunter.',
    entries: [
      e('badge', 'Badge', 'badge', 'Das Produkt'),
      e('heading', 'Überschrift', 'heading', 'Desktop & Mobile — eine Plattform.'),
      e('sub', 'Unterzeile', 'paragraph', 'Das SRT läuft im Browser und mobil auf dem Smartphone — mit identischer Datenbasis und Live-Status.'),
      e('label-desktop', 'Beschriftung unter dem Laptop', 'caption', 'Desktop · Web-Browser'),
      e('label-mobile', 'Beschriftung unter dem Smartphone', 'caption', 'Mobil · Smartphone'),
      e('mock-store', 'Smartphone-Mock-up — Einsatzort (Beispiel)', 'label', 'Elektronikmarkt Berlin'),
      e('mock-product', 'Smartphone-Mock-up — Produkt (Beispiel)', 'label', 'Smartwatch'),
      e('cap1-title', 'App-Kachel 1 — Titel', 'heading', 'Aufgaben einsehen'),
      e('cap1-desc', 'App-Kachel 1 — Text', 'paragraph', 'Einsätze, Zeiten und Standort — auf einen Blick im Smartphone.'),
      e('cap2-title', 'App-Kachel 2 — Titel', 'heading', 'GPS Check-in'),
      e('cap2-desc', 'App-Kachel 2 — Text', 'paragraph', 'Eincheckung nur vor Ort möglich. Zeiterfassung startet automatisch.'),
      e('cap3-title', 'App-Kachel 3 — Titel', 'heading', 'Zielerreichung tracken'),
      e('cap3-desc', 'App-Kachel 3 — Text', 'paragraph', 'Ziele und Verkaufstaktiken live einsehen und direkt handeln.'),
      e('cap4-title', 'App-Kachel 4 — Titel', 'heading', 'Abrechnung erhalten'),
      e('cap4-desc', 'App-Kachel 4 — Text', 'paragraph', 'Transparente Gehaltsabrechnung mit Provisionen direkt in der App.'),
      e('chip-1', 'Leiste — Chip 1', 'label', 'Mobil'),
      e('chip-2', 'Leiste — Chip 2', 'label', 'Einhändig'),
      e('chip-3', 'Leiste — Zusatz', 'caption', '· Intuitiv'),
    ],
  },
  {
    key: 'srt_modules', label: 'SRT — Funktionsumfang: 6 Module', pageGroupId: 'srt', pagePath: '/srt', description: 'Titel, Unterzeile und Beschreibung der sechs Module im Abschnitt „Funktionsumfang“.',
    entries: [
      e('m1-title', 'Modul 1 — Titel', 'heading', 'Einsatzplanung'),
      e('m1-subtitle', 'Modul 1 — Unterzeile', 'label', 'Drag-and-Drop Kalender'),
      e('m1-detail', 'Modul 1 — Beschreibung', 'paragraph', 'Plane Einsätze mit einem visuellen Drag-and-Drop-Kalender. Weise Aufgaben direkt Mitarbeitern zu, setze Prioritäten und verfolge den Status in Echtzeit.'),
      e('m2-title', 'Modul 2 — Titel', 'heading', 'Talentpool'),
      e('m2-subtitle', 'Modul 2 — Unterzeile', 'label', 'Von Recruiting bis Abrechnung'),
      e('m2-detail', 'Modul 2 — Beschreibung', 'paragraph', 'Von Bewerbung bis Abrechnung: Onboarding, Fotos, Qualifikationen, Verfügbarkeiten und Gehaltsdaten liegen zentral im SRT. Kein Tool-Wechsel.'),
      e('m3-title', 'Modul 3 — Titel', 'heading', 'GPS Check-in'),
      e('m3-subtitle', 'Modul 3 — Unterzeile', 'label', 'Nur vor Ort — keine Umgehung möglich'),
      e('m3-detail', 'Modul 3 — Beschreibung', 'paragraph', 'Das System prüft per GPS, ob der Mitarbeiter wirklich am Einsatzort ist. Erst dann wird die Zeiterfassung freigegeben. Transparenz für alle Seiten.'),
      e('m4-title', 'Modul 4 — Titel', 'heading', 'Datenintegration'),
      e('m4-subtitle', 'Modul 4 — Unterzeile', 'label', 'Online-Shops, Hersteller-Apps & Handelsdaten'),
      e('m4-detail', 'Modul 4 — Beschreibung', 'paragraph', 'Daten aus Online-Shops, Hersteller-Apps und dem Handel laufen im SRT in einer Oberfläche zusammen — inklusive WKZ-Handling.'),
      e('m5-title', 'Modul 5 — Titel', 'heading', 'Dokumenten-KI'),
      e('m5-subtitle', 'Modul 5 — Unterzeile', 'label', 'KI-gestützte Dokumentenverarbeitung'),
      e('m5-detail', 'Modul 5 — Beschreibung', 'paragraph', 'Rechnungen, Lieferscheine und Reports werden automatisch erkannt, klassifiziert und den richtigen Projekten zugeordnet. Spart Stunden manueller Arbeit.'),
      e('m6-title', 'Modul 6 — Titel', 'heading', 'Routenplanung'),
      e('m6-subtitle', 'Modul 6 — Unterzeile', 'label', 'In Entwicklung · ab 2026/27'),
      e('m6-detail', 'Modul 6 — Beschreibung', 'paragraph', 'Geplant für 2026/27: Das SRT soll Routen für den Außendienst planen — auf Basis von Einsatzorten und Zeitfenstern.'),
    ],
  },
  {
    key: 'srt_industries_items', label: 'SRT — Branchen & Use Cases: Karten', pageGroupId: 'srt', pagePath: '/srt', description: 'Die sechs Branchen-Karten mit je drei Stichpunkten.',
    entries: [
      e('i1-title', 'Karte 1 — Titel', 'heading', 'FMCG & Retail Execution'),
      e('i1-item-1', 'Karte 1 — Punkt 1', 'label', 'In-Store-Performance'),
      e('i1-item-2', 'Karte 1 — Punkt 2', 'label', 'Regal-Audits mit Fotodokumentation'),
      e('i1-item-3', 'Karte 1 — Punkt 3', 'label', 'POS-Material-Tracking'),
      e('i2-title', 'Karte 2 — Titel', 'heading', 'Beauty & Cosmetics'),
      e('i2-item-1', 'Karte 2 — Punkt 1', 'label', 'Beauty Advisor-Einsätze steuern'),
      e('i2-item-2', 'Karte 2 — Punkt 2', 'label', 'Für Retail und Events'),
      e('i2-item-3', 'Karte 2 — Punkt 3', 'label', 'Performance-Messung'),
      e('i3-title', 'Karte 3 — Titel', 'heading', 'Event & Promotional Staffing'),
      e('i3-item-1', 'Karte 3 — Punkt 1', 'label', 'Personaleinsätze steuern'),
      e('i3-item-2', 'Karte 3 — Punkt 2', 'label', 'Material- und Warenflüsse tracken'),
      e('i3-item-3', 'Karte 3 — Punkt 3', 'label', 'Erfolge messen & vergleichen'),
      e('i4-title', 'Karte 4 — Titel', 'heading', 'Field Sales & Territory'),
      e('i4-item-1', 'Karte 4 — Punkt 1', 'label', 'Regionen-basierte Planung'),
      e('i4-item-2', 'Karte 4 — Punkt 2', 'label', 'Besuchsberichte & Fotos'),
      e('i4-item-3', 'Karte 4 — Punkt 3', 'label', 'Analytics zu Regionen'),
      e('i5-title', 'Karte 5 — Titel', 'heading', 'Technischer Support CE'),
      e('i5-item-1', 'Karte 5 — Punkt 1', 'label', 'Servicetechniker-Einsätze planen'),
      e('i5-item-2', 'Karte 5 — Punkt 2', 'label', 'Warenfluss (Ersatzteile) tracken'),
      e('i5-item-3', 'Karte 5 — Punkt 3', 'label', 'Monitoring regionaler Abdeckung'),
      e('i6-title', 'Karte 6 — Titel', 'heading', 'Gesundheit & Pflege'),
      e('i6-item-1', 'Karte 6 — Punkt 1', 'label', 'Pharmaberater-Regionen managen'),
      e('i6-item-2', 'Karte 6 — Punkt 2', 'label', 'Besuche planen und dokumentieren'),
      e('i6-item-3', 'Karte 6 — Punkt 3', 'label', 'Compliance / Dokumentationen'),
    ],
  },
  {
    key: 'srt_proof_stats', label: 'SRT — In Zahlen: Kennzahlen', pageGroupId: 'srt', pagePath: '/srt', description: 'Die vier Kennzahlen im Abschnitt „SRT in Zahlen“ (Wert ohne „>“, das Zeichen wird automatisch davor gesetzt).',
    entries: [
      e('s1-value', 'Kennzahl 1 — Wert', 'stat', '1.000'),
      e('s1-label', 'Kennzahl 1 — Label', 'stat-label', 'Stores betreut'),
      e('s1-sublabel', 'Kennzahl 1 — Unterzeile', 'caption', 'In Sonic-Projekten'),
      e('s1-trend', 'Kennzahl 1 — Chip', 'caption', 'Im Handel'),
      e('s2-value', 'Kennzahl 2 — Wert', 'stat', '2 Mrd.'),
      e('s2-label', 'Kennzahl 2 — Label', 'stat-label', 'Umsatz generiert'),
      e('s2-sublabel', 'Kennzahl 2 — Unterzeile', 'caption', 'In Euro'),
      e('s2-trend', 'Kennzahl 2 — Chip', 'caption', 'Für unsere Kunden'),
      e('s3-value', 'Kennzahl 3 — Wert', 'stat', '1,3 Mio.'),
      e('s3-label', 'Kennzahl 3 — Label', 'stat-label', 'Einsätze getrackt'),
      e('s3-sublabel', 'Kennzahl 3 — Unterzeile', 'caption', 'Durch das SRT'),
      e('s3-trend', 'Kennzahl 3 — Chip', 'caption', 'Im SRT'),
      e('s4-value', 'Kennzahl 4 — Wert', 'stat', '1.800'),
      e('s4-label', 'Kennzahl 4 — Label', 'stat-label', 'Menschen im Talentpool'),
      e('s4-sublabel', 'Kennzahl 4 — Unterzeile', 'caption', 'Aktiv'),
      e('s4-trend', 'Kennzahl 4 — Chip', 'caption', 'DACH-weit'),
    ],
  },
  {
    key: 'srt_short_labels', label: 'SRT — Kurzlabels (Problem & Zahlen)', pageGroupId: 'srt', pagePath: '/srt', description: 'Kleine Kennzeichnungen über den drei Problem-Karten und über den vier Kennzahlen in „SRT in Zahlen“.',
    entries: [
      e('problem-1', 'Problem 1 — Label', 'label', 'Datensilos'),
      e('problem-2', 'Problem 2 — Label', 'label', 'Blinder Fleck'),
      e('problem-3', 'Problem 3 — Label', 'label', 'Späte Signale'),
      e('proof-1', 'Kennzahl 1 — Label oben', 'label', 'Stores'),
      e('proof-2', 'Kennzahl 2 — Label oben', 'label', 'Umsatz'),
      e('proof-3', 'Kennzahl 3 — Label oben', 'label', 'Einsätze'),
      e('proof-4', 'Kennzahl 4 — Label oben', 'label', 'Talentpool'),
    ],
  },
  {
    key: 'srt_nav', label: 'SRT — Seitennavigation', pageGroupId: 'srt', pagePath: '/srt', description: 'Beschriftungen der Sprungmarken-Leiste auf der SRT-Seite.',
    entries: [
      e('das-problem', 'Das Problem', 'label', 'Das Problem'),
      e('features', 'All-in-Software', 'label', 'All-in-Software'),
      e('funktionsumfang', 'Funktionsumfang', 'label', 'Funktionsumfang'),
      e('team-app', 'Team-App', 'label', 'Team-App'),
      e('zusammenarbeit', 'Zusammenarbeit', 'label', 'Zusammenarbeit'),
      e('datenfluss', 'Datenfluss', 'label', 'Datenfluss'),
      e('branchen', 'Branchen', 'label', 'Branchen'),
      e('srt-proof', 'SRT in Zahlen', 'label', 'SRT in Zahlen'),
      e('preise-zugang', 'Zugang', 'label', 'Zugang'),
    ],
  },
  {
    key: 'kontakt_form_texts', label: 'Kontakt — Formular-Texte', pageGroupId: 'kontakt', pagePath: '/kontakt', description: 'Zeile unter „Schreib uns“ und Bestätigung nach dem Absenden (Button: „Projekt anfragen“).',
    entries: [
      e('sub', 'Zeile unter der Überschrift', 'paragraph', 'Wir melden uns zeitnah.'),
      e('success', 'Bestätigung nach dem Absenden', 'paragraph', 'Wir melden uns zeitnah.'),
    ],
  },
];

export const REVIEW_DEFAULTS: Record<string, Record<string, string>> = Object.fromEntries(
  REVIEW_TEXT_SECTIONS.map((s) => [s.key, Object.fromEntries(s.entries.map((en) => [en.id, en.value]))]),
);
