import type { TextSection } from '@/lib/textStore';
import { e, section } from '@/lib/leistungenTextKit';

const P = '/leistungen/events-messen';

export const TEXT_SECTIONS: TextSection[] = [
  section('leistungen_events_hero_buttons', 'Events & Messen — Hero Buttons', P, 'Die beiden Buttons im Hero.', [
    e('cta-primary', 'Hero — Button (Mail)', 'cta', 'Beratungsgespräch buchen'),
    e('cta-secondary', 'Hero — Button (Seite)', 'cta', 'Events & Messen'),
  ]),
  section('leistungen_events_challenges', 'Events & Messen — Herausforderungen (3 Punkte)', P, 'Die drei Hover-Punkte unter „Ein Moment, viele Baustellen.“', [
    e('c1-title', 'Punkt 1 — Titel', 'subheading', 'Zu wenig Unique — alles schon gesehen'),
    e('c1-desc', 'Punkt 1 — Text', 'paragraph', 'Die Zielgruppen haben schon viel gesehen und erlebt. Für einzigartige Erlebnisse müssen Veranstaltungen auf allen Ebenen neu gedacht und sauber umgesetzt sein.'),
    e('c1-trigger', 'Punkt 1 — Frage', 'label', 'Auch dein Problem?'),
    e('c2-title', 'Punkt 2 — Titel', 'subheading', 'Zu viele Gewerke, zu viel Chaos'),
    e('c2-desc', 'Punkt 2 — Text', 'paragraph', 'Projektmanagement-Overhead, Inbox quillt über, alles wird erst auf den letzten Drücker fertig (oder auch nicht): Das passiert, ist aber vermeidbar.'),
    e('c2-trigger', 'Punkt 2 — Frage', 'label', 'Klingt bekannt?'),
    e('c3-title', 'Punkt 3 — Titel', 'subheading', 'Erfolge nicht messbar'),
    e('c3-desc', 'Punkt 3 — Text', 'paragraph', 'Daten zu bspw. Kosten und Erfolgen liegen verspätet bzw. unvollständig vor und können nicht optimal ausgewertet werden. Optimierungs-Möglichkeiten? Verborgen.'),
    e('c3-trigger', 'Punkt 3 — Frage', 'label', 'Frustrierend, oder?'),
  ]),
  section('leistungen_events_solutions', 'Events & Messen — Lösung (6 Karten)', P, 'Die sechs Scroll-Karten unter „Messe- und Event-Full Service.“', [
    e('eyebrow', 'Eyebrow', 'label', 'Die Lösung'),
    e('card1-accent', 'Karte 1 — Kategorie', 'label', 'Kreation'),
    e('card1-title', 'Karte 1 — Titel', 'subheading', 'Konzept'),
    e('card1-desc', 'Karte 1 — Text', 'paragraph', 'Vor dem Wow steht die Idee: Einzigartige Erlebnisse erfordern kreative (Stand-)Gestaltung, Venues und eine Umsetzung, die auffällt.'),
    e('card2-accent', 'Karte 2 — Kategorie', 'label', 'Bau & Technik'),
    e('card2-title', 'Karte 2 — Titel', 'subheading', 'Bau & Equipment'),
    e('card2-desc', 'Karte 2 — Text', 'paragraph', 'Die Ideen werden real: Mit Messe-, Möbel-, Modul- und Fahrzeugbau. Mit Bühnen, Displays, Installationen. Mit Licht, Sound, Screens und Interaktionen.'),
    e('card3-accent', 'Karte 3 — Kategorie', 'label', 'Team & Talent'),
    e('card3-title', 'Karte 3 — Titel', 'subheading', 'Geschultes Personal'),
    e('card3-desc', 'Karte 3 — Text', 'paragraph', 'Dediziert geschultes Personal für bestimmte Funktionen: Moderation, Musik, Catering, Logistik und Aufbau. Dazu Promoter, Messe-Hostessen und Brand Ambassadors, handverlesen aus unserem Talentpool.'),
    e('card4-accent', 'Karte 4 — Kategorie', 'label', 'Erlebnis'),
    e('card4-title', 'Karte 4 — Titel', 'subheading', 'Catering & Experiences'),
    e('card4-desc', 'Karte 4 — Text', 'paragraph', 'Essen, Trinken, Kunst und immersive Erlebnisse: So wird die Veranstaltung zum Erlebnis, das lange im Gedächtnis bleibt.'),
    e('card5-accent', 'Karte 5 — Kategorie', 'label', 'Logistik'),
    e('card5-title', 'Karte 5 — Titel', 'subheading', 'Logistik & Controlling'),
    e('card5-desc', 'Karte 5 — Text', 'paragraph', 'Ort und Zeit stehen fest. Wir sind da. Alles läuft. Dank unserem eigenen Warehouse und Logistikteam. Und die Kosten? Siehst du im Sonic Reporting Tool (SRT).'),
    e('card6-accent', 'Karte 6 — Kategorie', 'label', 'Kommunikation'),
    e('card6-title', 'Karte 6 — Titel', 'subheading', '(Digitale) Kommunikation'),
    e('card6-desc', 'Karte 6 — Text', 'paragraph', 'Von der Einladung über Goodie-Bags und Give-aways bis zum Live-Stream: damit deine Botschaften ankommen.'),
  ]),
  section('leistungen_events_process', 'Events & Messen — Ablauf (6 Schritte)', P, 'Titel, Text und Dauer der sechs Ablauf-Schritte und die Zeile über dem Button darunter. Der Button-Text selbst liegt in „Events & Messen — Content“.', [
    e('eyebrow', 'Eyebrow', 'label', 'Ablauf'),
    e('step1-title', 'Schritt 1 — Titel', 'subheading', 'Event-/Messe-Briefing'),
    e('step1-desc', 'Schritt 1 — Text', 'paragraph', 'Wir analysieren Ziele, Zielgruppe und Anforderungen — im Abgleich mit deiner Gesamtstrategie und deinem Budget.'),
    e('step1-time', 'Schritt 1 — Dauer', 'badge', '1–2 Tage'),
    e('step2-title', 'Schritt 2 — Titel', 'subheading', 'Konzeptentwicklung'),
    e('step2-desc', 'Schritt 2 — Text', 'paragraph', 'Kreatives Event-/Stand-/Modulkonzept inklusive Venue, Aktivierungsideen und Umsetzungsmöglichkeiten.'),
    e('step2-time', 'Schritt 2 — Dauer', 'badge', '1–4 Wochen'),
    e('step3-title', 'Schritt 3 — Titel', 'subheading', 'Personal-Auswahl'),
    e('step3-desc', 'Schritt 3 — Text', 'paragraph', 'Auswahl und Schulung des passenden Teams für deinen Event, meist aus dem Sonic Talentpool. Ggf. zusätzliches Recruiting.'),
    e('step3-time', 'Schritt 3 — Dauer', 'badge', '1–4 Wochen'),
    e('step4-title', 'Schritt 4 — Titel', 'subheading', 'Produktion & Vorbereitung'),
    e('step4-desc', 'Schritt 4 — Text', 'paragraph', 'Bookings, Modul-/Möbel-/Standbau, Druck, Programmierungen, Kommunikation, Logistik, Equipment-Check und finale Briefings vor Ort.'),
    e('step4-time', 'Schritt 4 — Dauer', 'badge', 'Nach Aufwand'),
    e('step5-title', 'Schritt 5 — Titel', 'subheading', 'Veranstaltung'),
    e('step5-desc', 'Schritt 5 — Text', 'paragraph', 'Professionelle Umsetzung mit Live-Support, Monitoring und Nachbereitung.'),
    e('step5-time', 'Schritt 5 — Dauer', 'badge', 'Event-Dauer'),
    e('step6-title', 'Schritt 6 — Titel', 'subheading', 'Reporting'),
    e('step6-desc', 'Schritt 6 — Text', 'paragraph', 'Detaillierte Auswertung mit KPIs, Insights und Optimierungsvorschlägen.'),
    e('step6-time', 'Schritt 6 — Dauer', 'badge', '3–5 Tage'),
    e('cta-kicker', 'Zeile über dem Button', 'label', 'Bereit für dein Event?'),
  ]),
  section('leistungen_events_formats', 'Events & Messen — Formate (3 Tabs)', P, 'Formate-Block mit den Tabs Events, Messen, Fahrzeuge & Module. Kategorien mit „|“ trennen.', [
    e('eyebrow', 'Eyebrow', 'label', 'Formate'),
    e('heading', 'Überschrift', 'heading', 'Deine Marke. Unsere Bühne.'),
    e('sub', 'Unterzeile', 'paragraph', 'Wähle ein Format und entdecke unsere Arbeit.'),
    e('tab1-label', 'Tab 1 — Name', 'label', 'Events'),
    e('tab1-headline', 'Tab 1 — Überschrift', 'subheading', 'Marken live erlebbar machen.'),
    e('tab1-sub', 'Tab 1 — Text', 'paragraph', 'Von der exklusiven Produktpreview bis zum hybriden Kongress.'),
    e('tab1-pills', 'Tab 1 — Kategorien (mit | trennen)', 'tag', 'Consumer & Corporate Events | Händler-Events | Kick-Off-Events | Kongresse & Tagungen | PR-Events | Produktlaunches | Promotions | Roadshows & Festivals'),
    e('tab2-label', 'Tab 2 — Name', 'label', 'Messen'),
    e('tab2-headline', 'Tab 2 — Überschrift', 'subheading', 'Messen verbinden Menschen mit Marken.'),
    e('tab2-sub', 'Tab 2 — Text', 'paragraph', 'Messe-Komplettpakete in allen Größen — von der Idee bis zum Abbau.'),
    e('tab2-pills', 'Tab 2 — Kategorien (mit | trennen)', 'tag', 'Messebau & Ausstattung | Messedesign | Messe-Events | On- & Offline-Foren'),
    e('tab3-label', 'Tab 3 — Name', 'label', 'Fahrzeuge & Module'),
    e('tab3-headline', 'Tab 3 — Überschrift', 'subheading', 'Deine Roadshow. Mobil und flexibel.'),
    e('tab3-sub', 'Tab 3 — Text', 'paragraph', 'Von uns gebaute Eventfahrzeuge oder transportierbare Module. Inklusive Ideen, Personal und laufendem Betrieb.'),
    e('tab3-pills', 'Tab 3 — Kategorien (mit | trennen)', 'tag', 'Eventtrucks | Eventcontainer | Eventmodule | Promotionfahrzeuge'),
    e('label-categories', 'Label „Kategorien“', 'label', 'Kategorien'),
    e('label-examples', 'Label „Beispiele“', 'label', 'Beispiele'),
    e('cta-label', 'Button', 'cta', 'Beratungsgespräch buchen'),
  ]),
  section('leistungen_events_cta', 'Events & Messen — Kontakt-Box', P, 'Abschluss-Box am Seitenende. Checkliste mit „|“ trennen.', [
    e('headline', 'Überschrift', 'heading', 'Bereit für deinen'),
    e('headline-accent', 'Überschrift — Akzent', 'heading', 'nächsten Auftritt?'),
    e('subline', 'Unterzeile', 'paragraph', 'Lass uns in 30 Minuten besprechen, wie wir deine Marke zum Erlebnis machen.'),
    e('check-items', 'Checkliste (mit | trennen)', 'list-item', 'Kostenfreies 30-Minuten-Strategiegespräch | Deine Ziele, unser modulares System | Einblick in unsere Arbeitsweise und SRT | Erste Einschätzung zur Timeline'),
    e('cta-label', 'Button', 'cta', 'Beratungsgespräch buchen'),
  ]),
];
