import type { TextSection } from '@/lib/textStore';
import { e, section } from '@/lib/leistungenTextKit';

const P = '/leistungen';

export const TEXT_SECTIONS: TextSection[] = [
  section('leistungen_overview_hero', 'Leistungen — Hero', P, 'Hero der Leistungen-Übersicht: Überschrift mit wechselndem Wort, Texte, Buttons.', [
    e('eyebrow', 'Eyebrow', 'badge', 'Leistungen'),
    e('h1', 'H1 — fester Teil', 'heading', 'Manpower trifft'),
    e('h1-words', 'H1 — wechselnde Wörter (mit | trennen)', 'tag', 'ROI | Retail | POS | Events | Staffing | Video | Data | Growth'),
    e('lead', 'Leadzeile', 'paragraph', 'Full Service für deine Marken und Produkte im Retail'),
    e('sub', 'Unterzeile', 'paragraph', 'Von Daten & Software über Personal & Staffing bis zu POS, Video und Events: alles aus einer Hand. Daten liefern die Fakten, Menschen den Unterschied.'),
    e('cta-secondary', 'Button 2 (Button 1 = CTAs → „Termin“)', 'cta', 'Alle Leistungen entdecken'),
  ]),
  section('leistungen_overview_stats', 'Leistungen — Zahlen', P, 'Vier Kennzahlen (nur Zahlen aus der Agenturpräsentation). Der Zahlenteil im Wert zählt automatisch hoch.', [
    e('eyebrow', 'Eyebrow', 'label', 'Unsere Zahlen'),
    e('heading', 'Überschrift — Teil 1', 'heading', 'Track Record,'),
    e('heading-accent', 'Überschrift — Teil 2 (lime)', 'heading', 'der überzeugt.'),
    e('stat1-value', 'Kennzahl 1 — Wert', 'stat', '>1.000'),
    e('stat1-label', 'Kennzahl 1 — Label', 'stat-label', 'Stores betreut'),
    e('stat1-sub', 'Kennzahl 1 — Zusatz', 'caption', 'Für über 15 Kunden'),
    e('stat2-value', 'Kennzahl 2 — Wert', 'stat', '>2 Mrd. €'),
    e('stat2-label', 'Kennzahl 2 — Label', 'stat-label', 'Umsatz generiert'),
    e('stat2-sub', 'Kennzahl 2 — Zusatz', 'caption', 'Für unsere Kunden'),
    e('stat3-value', 'Kennzahl 3 — Wert', 'stat', '>1.800'),
    e('stat3-label', 'Kennzahl 3 — Label', 'stat-label', 'Menschen im Talentpool'),
    e('stat3-sub', 'Kennzahl 3 — Zusatz', 'caption', '200+ Promoter:innen im Einsatz'),
    e('stat4-value', 'Kennzahl 4 — Wert', 'stat', '>1,3 Mio.'),
    e('stat4-label', 'Kennzahl 4 — Label', 'stat-label', 'Einsätze durchgeführt'),
    e('stat4-sub', 'Kennzahl 4 — Zusatz', 'caption', 'Wir „machen“ seit 2007'),
  ]),
  section('leistungen_overview_services', 'Leistungen — Leistungsspektrum (4 Kategorien)', P, 'Überschrift und die vier Kategorie-Tabs. Tags mit | trennen.', [
    e('eyebrow', 'Eyebrow', 'label', 'Leistungsspektrum'),
    e('heading', 'Überschrift — Zeile 1', 'heading', 'Vier Kategorien.'),
    e('heading-accent', 'Überschrift — Zeile 2 (lime Wort)', 'heading', 'System'),
    e('sub', 'Unterzeile', 'paragraph', 'Jede Leistung einzeln buchbar — oder als integriertes Full-Service-Paket.'),
    e('s1-category', 'Kategorie 1 — Name', 'label', 'Daten & Software'),
    e('s1-headline', 'Kategorie 1 — Titel', 'subheading', 'Echtzeit-Intelligenz'),
    e('s1-sub', 'Kategorie 1 — Text', 'paragraph', 'Datentransparenz ab dem ersten Einsatz — im Sonic Reporting Tool, seit 2008 in über 21 Versionen weiterentwickelt. Keine Silos: Du entscheidest auf Basis echter Zahlen.'),
    e('s1-cta', 'Kategorie 1 — Button 1', 'cta', 'SRT entdecken'),
    e('s1-cta2', 'Kategorie 1 — Button 2', 'cta', 'Forecasting ansehen'),
    e('s1-tags', 'Kategorie 1 — Tags', 'tag', 'SRT | Forecasting | KPI-Tracking'),
    e('s2-category', 'Kategorie 2 — Name', 'label', 'Personal & Staffing'),
    e('s2-headline', 'Kategorie 2 — Titel', 'subheading', 'Geschulte Talente'),
    e('s2-sub', 'Kategorie 2 — Text', 'paragraph', 'Über 1.800 Menschen im Talentpool, 200+ Promoter:innen im Einsatz. Ausgewählt nach Profil, Know-how, Erfahrung und Marken-Fit — geschult und persönlich betreut, deutschlandweit.'),
    e('s2-cta', 'Kategorie 2 — Button 1', 'cta', 'Talentpool erkunden'),
    e('s2-cta2', 'Kategorie 2 — Button 2', 'cta', 'Staffing ansehen'),
    e('s2-tags', 'Kategorie 2 — Tags', 'tag', 'Recruiting | Field Force | Standort-Check-in'),
    e('s3-category', 'Kategorie 3 — Name', 'label', 'POS & Live Video'),
    e('s3-headline', 'Kategorie 3 — Titel', 'subheading', 'Sichtbarkeit am POS'),
    e('s3-sub', 'Kategorie 3 — Text', 'paragraph', 'Physische Präsenz trifft digitale Live-Beratung. Vom Regal bis zum QR-Code: online für Convenience & Information, offline für Erlebnis & Vertrauen.'),
    e('s3-cta', 'Kategorie 3 — Button 1', 'cta', 'POS Full Service'),
    e('s3-cta2', 'Kategorie 3 — Button 2', 'cta', 'Live Video Promotion'),
    e('s3-tags', 'Kategorie 3 — Tags', 'tag', 'POS-Display | Shop-in-Shop | Live Video'),
    e('s4-category', 'Kategorie 4 — Name', 'label', 'Events & Logistik'),
    e('s4-headline', 'Kategorie 4 — Titel', 'subheading', 'Erlebbare Markenpräsenz'),
    e('s4-sub', 'Kategorie 4 — Text', 'paragraph', 'Von der Aktivierungsfläche bis zum Warenlager — aus einer Hand. Roadshows, Messen, Instore-Events, Konfektionierung. Über 200 Events, mehr als 30.000 Kontakte.'),
    e('s4-cta', 'Kategorie 4 — Button 1', 'cta', 'Events & Messen'),
    e('s4-cta2', 'Kategorie 4 — Button 2', 'cta', 'Warehouse & Logistik'),
    e('s4-tags', 'Kategorie 4 — Tags', 'tag', 'Roadshows | Events | Warehouse'),
    e('help-heading', 'Frage-Leiste — Überschrift (Button = CTAs → „Termin“)', 'subheading', 'Noch Fragen zum Leistungsumfang?'),
  ]),
  section('leistungen_overview_ways', 'Leistungen — Retail-Schallmauer (3 Wege)', P, 'Die drei Wege Markteintritt, Absatz steigern, Omnichannel. Listen und Tags mit | trennen.', [
    e('eyebrow', 'Eyebrow', 'label', 'Die Retail-Schallmauer'),
    e('heading', 'Überschrift — Teil 1', 'heading', 'Dein Weg zum'),
    e('heading-accent', 'Überschrift — Teil 2 (lime)', 'heading', 'Retail-Erfolg'),
    e('sub', 'Unterzeile', 'paragraph', 'Wähle deinen Pfad — oder kombiniere alle drei.'),
    e('w1-title', 'Weg 1 — Name', 'label', 'Markteintritt'),
    e('w1-headline', 'Weg 1 — Titel', 'subheading', 'Neu im Markt. Schnell sichtbar.'),
    e('w1-desc', 'Weg 1 — Text', 'paragraph', 'Dein Produkt ist kaufbereit, aber noch unbekannt? Wir ändern das. Mit Menschen, die deine Marke verstehen und sie am Point of Sale, per Video und bei Events erlebbar machen.'),
    e('w1-bullets', 'Weg 1 — Punkte', 'list-item', 'Brand Ambassadors am POS | Datenbasierte Standortplanung mit SRT | Launch-Events & Promotions | Live-Reporting ab Tag 1'),
    e('w1-cta', 'Weg 1 — Button', 'cta', 'Markteintritt planen'),
    e('w1-tags', 'Weg 1 — Tags', 'tag', 'Markteinführung | POS | Live-Kommunikation'),
    e('w2-title', 'Weg 2 — Name', 'label', 'Absatz steigern'),
    e('w2-headline', 'Weg 2 — Titel', 'subheading', 'Produkt im Regal. Abverkauf mit Plan.'),
    e('w2-desc', 'Weg 2 — Text', 'paragraph', 'Unsere Field-Force-Teams sind deine verlängerte Vertriebsmannschaft am POS: datenbasiert geplant, lückenlos reportet. Du weißt vorher, womit du realistisch rechnen kannst.'),
    e('w2-bullets', 'Weg 2 — Punkte', 'list-item', 'Geschulte Promoter mit Produktwissen | Forecasting vor dem ersten Einsatz | Standort-Check-in & Live-Dashboard | Kontinuierliche Optimierung'),
    e('w2-cta', 'Weg 2 — Button', 'cta', 'Absatz steigern'),
    e('w2-tags', 'Weg 2 — Tags', 'tag', 'Field Force | Retail | ROI'),
    e('w3-title', 'Weg 3 — Name', 'label', 'Omnichannel'),
    e('w3-headline', 'Weg 3 — Titel', 'subheading', 'Human Power in allen Kanälen.'),
    e('w3-desc', 'Weg 3 — Text', 'paragraph', 'Die größte Lücke im Omnichannel? Beratung. Unsere Antwort: Live-Video-Kaufberatung, erreichbar im Online-Shop oder per QR-Code auf der Verpackung.'),
    e('w3-bullets', 'Weg 3 — Punkte', 'list-item', 'Live-Video im Online-Shop | QR-Code auf Verpackung & POS-Display | Geschulte Video-Berater aus dem Talentpool | Skalierbar vom Test bis zum Dauerbetrieb'),
    e('w3-cta', 'Weg 3 — Button', 'cta', 'Omnichannel starten'),
    e('w3-tags', 'Weg 3 — Tags', 'tag', 'Live-Video | E-Commerce | Conversions'),
  ]),
  section('leistungen_overview_cta', 'Leistungen — Kontaktbox', P, 'Kontaktbox am Seitenende: kurze Frage, eine Zeile. Button und Zeile darunter: CTAs — Button-Texte.', [
    e('headline', 'Überschrift — Teil 1', 'heading', 'Welche Leistung'),
    e('headline-accent', 'Überschrift — Teil 2 (lime)', 'heading', 'passt zu dir?'),
    e('subline', 'Unterzeile', 'paragraph', 'In 30 Minuten klären wir, was zu deinem Ziel passt.'),
  ]),
];
