import type { TextSection } from '@/lib/textStore';
import { e, section } from '@/lib/leistungenTextKit';

const P = '/leistungen/staff-as-a-service';

export const TEXT_SECTIONS: TextSection[] = [
  section('leistungen_staff_hero_stats', 'Staff as a Service — Hero Kennzahlen & Buttons', P,
    'Die drei Kennzahlen unter dem Hero-Text und der zweite Hero-Button (Button 1: CTAs — Button-Texte). Nur Zahlen aus der Agenturpräsentation verwenden.', [
      e('stat-1-value', 'Hero — Kennzahl 1 — Wert', 'stat', '>1.800'),
      e('stat-1-label', 'Hero — Kennzahl 1 — Label', 'stat-label', 'Menschen im Talentpool'),
      e('stat-2-value', 'Hero — Kennzahl 2 — Wert', 'stat', '>1,3 Mio.'),
      e('stat-2-label', 'Hero — Kennzahl 2 — Label', 'stat-label', 'Einsätze'),
      e('stat-3-value', 'Hero — Kennzahl 3 — Wert', 'stat', '200+'),
      e('stat-3-label', 'Hero — Kennzahl 3 — Label', 'stat-label', 'Promoter:innen im Einsatz'),
      e('btn-secondary', 'Hero — Button sekundär (Link Talentpool)', 'cta', 'Talentpool entdecken'),
    ]),

  section('leistungen_staff_challenges', 'Staff as a Service — Herausforderungen (3 Punkte)', P,
    'Die drei Herausforderungs-Punkte (Titel, Text, Hover-Frage). Überschrift und Subline liegen in „Staff as a Service — Content“.', [
      e('c1-title', 'Punkt 1 — Titel', 'subheading', 'Spezielle Talente — schwer zu finden'),
      e('c1-desc', 'Punkt 1 — Text', 'paragraph', 'Motivierbare Fachkräfte, die Lust auf wechselnde Einsätze haben, sind über reguläres Recruiting bzw. Personaldienstleister schwer zu finden.'),
      e('c1-trigger', 'Punkt 1 — Hover-Frage', 'label', 'Auch deine Erfahrung?'),
      e('c2-title', 'Punkt 2 — Titel', 'subheading', 'Payroll? Jeden Monat ein Kraftakt'),
      e('c2-desc', 'Punkt 2 — Text', 'paragraph', 'Stundenlöhne, Provisionen, Pauschalen, Sozialversicherung: für jede Person jeden Monat anders. Das bindet in der internen Lohnbuchhaltung viel Zeit.'),
      e('c2-trigger', 'Punkt 2 — Hover-Frage', 'label', 'Klingt vertraut?'),
      e('c3-title', 'Punkt 3 — Titel', 'subheading', 'Erfolge schwer messbar — Optimierung nach Gefühl'),
      e('c3-desc', 'Punkt 3 — Text', 'paragraph', 'Reportings lassen sich oft erst weit im Nachhinein erstellen, da die Daten zu Einsätzen, Absatz und Lohn-Vollkosten erst mit Verzögerung vorliegen.'),
      e('c3-trigger', 'Punkt 3 — Hover-Frage', 'label', 'Schon frustriert?'),
    ]),

  section('leistungen_staff_solution', 'Staff as a Service — Lösung (4 Karten)', P,
    'Eyebrow und die vier Lösungs-Karten. Überschrift und Subline liegen in „Staff as a Service — Content“.', [
      e('eyebrow', 'Lösung — Eyebrow', 'label', 'Die Lösung'),
      e('s1-accent', 'Karte 1 — Kategorie', 'label', 'HR & Sourcing'),
      e('s1-title', 'Karte 1 — Titel', 'subheading', 'Recruiting'),
      e('s1-desc', 'Karte 1 — Text', 'paragraph', 'Wir finden Talente in unserem Talentpool und on top über bewährte Recruiting-Strategien – ausgewählt nach Profil, Know-how, Erfahrung und Marken-Fit. Passend für deine Aufgaben. Mit digitalen Arbeitsverträgen. Null Arbeit für deine HR-Abteilung.'),
      e('s2-accent', 'Karte 2 — Kategorie', 'label', 'Training'),
      e('s2-title', 'Karte 2 — Titel', 'subheading', 'Onboarding & Schulungen'),
      e('s2-desc', 'Karte 2 — Text', 'paragraph', 'Aufs Onboarding sind wir spezialisiert: Wir haben (Sales-)Trainer und kennen uns sehr gut mit Produkt- und Markenschulungen aus.'),
      e('s3-accent', 'Karte 3 — Kategorie', 'label', 'Finance & Admin'),
      e('s3-title', 'Karte 3 — Titel', 'subheading', 'Payroll'),
      e('s3-desc', 'Karte 3 — Text', 'paragraph', 'Wer bekommt wofür wie viel Geld, basierend auf bspw. Arbeitszeiten und Erfolgsfaktoren? Wir managen die Payroll komplett, auf Basis der Daten unseres Sonic Reporting Tools (SRT). Fair. Transparent. Nachvollziehbar.'),
      e('s4-accent', 'Karte 4 — Kategorie', 'label', 'Transparenz'),
      e('s4-title', 'Karte 4 — Titel', 'subheading', 'Kosten-Nutzen-Transparenz'),
      e('s4-desc', 'Karte 4 — Text', 'paragraph', 'Du kannst jederzeit alle Daten, u. a. (Lohn-)Kosten, einsehen und dir reporten lassen.'),
    ]),

  section('leistungen_staff_process', 'Staff as a Service — Ablauf (6 Schritte)', P,
    'Eyebrow, Subline und die sechs Prozessschritte (Titel, Text, Dauer). Die Überschrift liegt in „Staff as a Service — Content“. Dauer gemäß Recruiting-Timeline der Agenturpräsentation.', [
      e('eyebrow', 'Ablauf — Eyebrow', 'label', 'Ablauf'),
      e('sub', 'Ablauf — Subline', 'paragraph', 'Volle Kostenkontrolle, volle Flexibilität, volle Entlastung – in einem effizienten, reibungslosen Prozess.'),
      e('step-1-title', 'Schritt 1 — Titel', 'subheading', 'Bedarfsanalyse'),
      e('step-1-desc', 'Schritt 1 — Text', 'paragraph', 'Wir verstehen dein Geschäft, deine Produkte und deinen Personalbedarf. Welche Rollen, welche Skills und welchen Umfang brauchst du? Dazu klären wir Arbeitsort, Vertragsbedingungen, Gehaltsbestandteile und das Persona-Briefing.'),
      e('step-1-time', 'Schritt 1 — Dauer', 'badge', '1 Woche'),
      e('step-2-title', 'Schritt 2 — Titel', 'subheading', 'Recruiting & Auswahl'),
      e('step-2-desc', 'Schritt 2 — Text', 'paragraph', 'Erst gezielte Sichtung im Talentpool, bei Bedarf Neurekrutierung, z. B. per Paid-Media-Kampagne. Dann Interviews, finale Auswahl – auf Wunsch im gemeinsamen Interview mit dir – und digitale Arbeitsverträge. Alles in Abstimmung mit dir.'),
      e('step-2-time', 'Schritt 2 — Dauer', 'badge', 'Je nach Profil'),
      e('step-3-title', 'Schritt 3 — Titel', 'subheading', 'Schulung & Onboarding'),
      e('step-3-desc', 'Schritt 3 — Text', 'paragraph', 'Intensives Produkttraining, Marken-Briefing, Verkaufstechniken: Dein Team ist ab Tag 1 einsatzbereit.'),
      e('step-3-time', 'Schritt 3 — Dauer', 'badge', '2–5 Tage'),
      e('step-4-title', 'Schritt 4 — Titel', 'subheading', 'Einsatz & Steuerung'),
      e('step-4-desc', 'Schritt 4 — Text', 'paragraph', 'Koordinierte Einsatzplanung über das Sonic Reporting Tool (SRT). Dein Personal ist zur richtigen Zeit am richtigen Ort, und du hast darauf Live-Zugriff.'),
      e('step-4-time', 'Schritt 4 — Dauer', 'badge', 'Ongoing'),
      e('step-5-title', 'Schritt 5 — Titel', 'subheading', 'Performance & Optimierung'),
      e('step-5-desc', 'Schritt 5 — Text', 'paragraph', 'Laufendes Monitoring, Coaching, Team-Rotation bei Bedarf. Wir optimieren, bis die Zahlen stimmen.'),
      e('step-5-time', 'Schritt 5 — Dauer', 'badge', 'Ongoing'),
      e('step-6-title', 'Schritt 6 — Titel', 'subheading', 'Abrechnung'),
      e('step-6-desc', 'Schritt 6 — Text', 'paragraph', 'Wir erstellen für dich übersichtliche Rechnungen, die deine Buchhaltungs- und Controlling-Prozesse vereinfachen.'),
      e('step-6-time', 'Schritt 6 — Dauer', 'badge', 'Ongoing'),
    ]),

  section('leistungen_staff_specs', 'Staff as a Service — Einsatzbereiche (6 Karten)', P,
    'Eyebrow, Subline und die sechs Einsatzbereich-Karten. Die Überschrift liegt in „Staff as a Service — Content“.', [
      e('eyebrow', 'Einsatzbereiche — Eyebrow', 'label', 'Unsere Spezialisierung'),
      e('sub', 'Einsatzbereiche — Subline', 'paragraph', 'Per Arbeitnehmerüberlassung, befristeter Teil-/Vollzeit oder kurzfristiger Beschäftigung: 6 Einsatzbereiche — ein Ansprechpartner bei Sonic.'),
      e('sp1-accent', 'Karte 1 — Kategorie', 'label', 'POS & Retail'),
      e('sp1-title', 'Karte 1 — Titel', 'subheading', 'Sales Activation'),
      e('sp1-desc', 'Karte 1 — Text', 'paragraph', 'Sales-Profis, geschult auf zielgerichtete Beratung. Sie vermitteln Features, stärken deine Marktposition und machen aus Interessenten Käufer.'),
      e('sp2-accent', 'Karte 2 — Kategorie', 'label', 'B2B Vertrieb'),
      e('sp2-title', 'Karte 2 — Titel', 'subheading', 'Sales Außendienst'),
      e('sp2-desc', 'Karte 2 — Text', 'paragraph', 'Mit kundenexklusiven Vertriebsaußendienst-Mitarbeitern stellen wir den Erfolg auch im mehrstufigen Vertrieb sicher. Multifunktional einsetzbar.'),
      e('sp3-accent', 'Karte 3 — Kategorie', 'label', 'Markenbildung'),
      e('sp3-title', 'Karte 3 — Titel', 'subheading', 'Brand Activation'),
      e('sp3-desc', 'Karte 3 — Text', 'paragraph', 'Brand-Activation-Mitarbeiter geben deiner Marke ein Gesicht. Als Verbindung zwischen Interessenten und Marke schaffen sie eine Vertrauensbasis.'),
      e('sp4-accent', 'Karte 4 — Kategorie', 'label', 'Handel & Regal'),
      e('sp4-title', 'Karte 4 — Titel', 'subheading', 'Merchandising'),
      e('sp4-desc', 'Karte 4 — Text', 'paragraph', 'Eine starke Warenpräsentation am POS braucht fleißige Hände und Doing-Things-Mentalität. Ob 360-Grad-Außendienst oder spezialisierte Teams.'),
      e('sp5-accent', 'Karte 5 — Kategorie', 'label', 'Shop-in-Shop'),
      e('sp5-title', 'Karte 5 — Titel', 'subheading', 'Shop-in-Shop Staff'),
      e('sp5-desc', 'Karte 5 — Text', 'paragraph', 'Wir finden die passenden Menschen für Shop-in-Shop-Outlets: Beratung, Demos, Verkauf, Regalpflege und mehr. Mit Schichtsystem und Plan B.'),
      e('sp6-accent', 'Karte 6 — Kategorie', 'label', 'Know-how'),
      e('sp6-title', 'Karte 6 — Titel', 'subheading', 'Training'),
      e('sp6-desc', 'Karte 6 — Text', 'paragraph', 'Regelmäßige Trainings stellen sicher, dass dein Team und die Teams deiner Handelspartner immer über aktuelles Know-how verfügen.'),
    ]),

  section('leistungen_staff_cta', 'Staff as a Service — Kontakt-Box', P,
    'Abschluss-Box am Seitenende: kurze Frage, eine Zeile. Button und Zeile darunter: CTAs — Button-Texte.', [
      e('headline', 'Kontakt — Überschrift', 'heading', 'Personal'),
      e('headline-accent', 'Kontakt — Überschrift (Akzent)', 'heading', 'gesucht?'),
      e('subline', 'Kontakt — Subline', 'paragraph', 'Wir klären, welches Staffing-Modell zu deinem Projekt passt.'),
    ]),
];
